In [1]:
import numpy as np
import pandas as pd

In [5]:
sal = pd.read_csv('SalariesInSanFranciscoDataSet.csv')

C:\Users\USER\AppData\Local\Temp\ipykernel_23644\3184198875.py:1: DtypeWarning: Columns (0: BasePay, 1: OvertimePay, 2: OtherPay, 3: Benefits, 4: Status) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.read_csv('SalariesInSanFranciscoDataSet.csv')

In [6]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [18]:
sal.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [33]:
def clears(pay):
    if pay=='Not Provided':
        return np.nan
    else: 
        return pay

In [52]:
sal['BasePay'] = sal['BasePay'].apply(clears)

In [60]:
sal['BasePay'].isna().sum()

np.int64(609)

In [64]:
sal['BasePay']= sal['BasePay'].astype('float32')

In [65]:
sal['BasePay'].mean()

np.float32(66325.45)

In [76]:
sal['OvertimePay'] =sal['OvertimePay'].astype('float32')

In [77]:
sal['OvertimePay'].max()

np.float32(245131.88)

In [82]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

In [90]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [94]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.1875,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

In [95]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()] # the record it incorrect because his total pay is in minus which in impossible.

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0,-618.13,-618.13,2014,NaN,San Francisco,PT

In [98]:
sal.groupby('Year')['BasePay'].mean()

Year
2011    63595.956495
2012    65436.406873
2013    69630.030258
2014    66564.421986
Name: BasePay, dtype: float64

In [100]:
sal['JobTitle'].nunique()

2159

In [103]:
sal['JobTitle'].value_counts().sort_values(ascending = False).head()

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [123]:
print((sal[sal['Year'] == 2013]['JobTitle'].value_counts() == 1).sum())

202

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148646,148647,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.0,0.0,2014,NaN,San Francisco,NaN

In [131]:
sal['JobTitle'] = sal['JobTitle'].astype('str')

In [166]:
count = 0
for i in sal['JobTitle'].str.title():
    if 'Chief' in i:
        count +=1
count

627

In [173]:
sal['JobTitle'].str.contains('Chief', case = False).sum()

np.int64(627)

In [162]:
sal['title_len'] = sal['JobTitle'].apply(lambda x: len(x))

In [170]:
sal[['title_len','TotalPayBenefits']].corr()

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000